language: java

services:
  - mysql

before_script:
- mysql -u root -e 'GRANT ALL ON *.* TO 'root'@'localhost';'

test:
- mysql -u root -p root -e 'GRANT ALL ON *.* TO 'root'@'localhost';'
  dist:precise

before_install:
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql_upgrade -u root -pnew_password
  - service mysql restart
